# Generated by Django 4.1.6 on 2023-02-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_name", models.CharField(max_length=200)),
                ("opti1", models.CharField(max_length=200)),
                ("opti2", models.CharField(max_length=200)),
                ("opti3", models.CharField(max_length=200)),
                ("opti4", models.CharField(max_length=200)),
                ("ans", models.CharField(max_length=200)),
            ],
        ),
    ]
